name: Build nx-hbloader - 20260324
on:
  workflow_dispatch:

jobs:
  build:
    name: Build and Release nx-hbloader
    runs-on: ubuntu-latest
    permissions:
      contents: write
    container: devkitpro/devkita64:latest

    steps:
      - name: Update latest libnx
        run: |
          git config --global --add safe.directory "*"
          git clone --recurse-submodules https://github.com/switchbrew/libnx.git
          cd libnx
          make install -j$(nproc)

      - name: Checkout latest code
        uses: actions/checkout@v6
        with:
          clean: true
          fetch-depth: 0
          fetch-tags: true
          submodules: recursive

      - name: Extract version
        run: |
          VERSION=$(awk '/^APP_VERSION/ {print $3}' Makefile | head -n 1)
          SHORT_HASH=$(git rev-parse --short=7 HEAD)

          echo "TAG_NAME=v${VERSION}-${SHORT_HASH}" >> "$GITHUB_ENV"
          echo "RELEASE_NAME=nx-hbloader v${VERSION} (${SHORT_HASH})" >> "$GITHUB_ENV"

      - name: Build nx-hbloader
        run: |
          export DEVKITPRO=/opt/devkitpro
          make RELEASE=1 -j$(nproc)

      - name: Upload release asset
        uses: softprops/action-gh-release@v2
        with:
          tag_name: ${{ env.TAG_NAME }}
          name: ${{ env.RELEASE_NAME }}
          draft: false
          prerelease: false
          generate_release_notes: true
          make_latest: true
          files: |
            hbl.nsp
